CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE STUDENT2 (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(10)
);


INSERT INTO STUDENT 
(NAME, AGE, CITY) VALUES
('VANSH', 19, 'KADI'),
('NIKHIL', 17, 'KADI'),
('ZEESHAN', 20, 'SAUDI'),
('PREM', 18, 'KADI'),
('NIRMESH', 50, 'AHMEDABAD'),
('TUSHAR', 19, 'MODASHA');

ALTER TABLE STUDENT ADD COLUMN PHONE_NO VARCHAR(10);

ALTER TABLE STUDENT MODIFY COLUMN PHONE_NO VARCHAR(15);

ALTER TABLE STUDENT ADD COLUMN LINKEDIN_URL VARCHAR(200);

ALTER TABLE STUDENT DROP COLUMN LINKEDIN_URL;

ALTER TABLE STUDENT RENAME COLUMN PHONE_NO TO MOBILE_NO;

ALTER TABLE STUDENT RENAME TO BCA_STUDENTS;
SELECT * FROM BCA_STUDENTS;

ALTER TABLE BCA_STUDENTS RENAME TO STUDENTS;
SELECT * FROM STUDENTS;