CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE STUDENTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(10)
);


INSERT INTO STUDENTS
(NAME, AGE, CITY) VALUES
('VANSH', 19, 'KADI'),
('NIKHIL', 17, 'KADI'),
('ZEESHAN', 20, 'SAUDI'),
('PREM', 18, 'KADI'),
('NIRMESH', 50, 'AHMEDABAD'),
('TUSHAR', 19, 'MODASHA');

UPDATE STUDENTS SET CITY = 'AHMEDABAD' WHERE ID = 1;
SELECT * FROM STUDENTS;

UPDATE STUDENTS SET AGE = '18' WHERE AGE < 18;

UPDATE STUDENTS SET NAME = 'NIKHIL P', AGE = 17 WHERE ID = 2;


