CREATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20),
DEPARTMENT VARCHAR(10) NOT NULL,
SALARY DECIMAL(10, 2),
CITY VARCHAR(15),
IS_ACTIVE BOOLEAN DEFAULT TRUE
);

INSERT INTO EMPLOYEES 
(NAME, EMAIL, DEPARTMENT, SALARY, CITY, IS_ACTIVE) VALUES
('NIKHIL PARMAR', 'nikhil@gamil.com', 'BCA', 19000, 'KADI', TRUE),
('PREM DANTANI', 'prem@gamil.com', 'BBA', 29000, 'KADI', TRUE),
('NIRMESH PATEL', 'nirmesh@gamil.com', 'MCA', 21000, 'AHMEDABAD', FALSE),
('ADITYA JANI', 'aditya@gamil.com', 'BCA', 31000, 'GANDHINAGAR', FALSE),
('TUSHAR VALAND', 'tushar@gamil.com', 'MCA', 23000, 'VADODARA', TRUE),
('MAHOMMAD ZEESHAN', 'zeeshan@gamil.com', 'BBA', 31000, 'AHMEDABAD', FALSE);

SELECT * FROM EMPLOYEES;

-- 1.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'BCA' AND SALARY > 25000;

-- 2.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'BCA' OR DEPARTMENT = 'MCA';

-- 3.
UPDATE EMPLOYEES SET SALARY = SALARY + 5000 WHERE DEPARTMENT = 'BCA' OR DEPARTMENT = 'MCA';

-- 4.
DELETE FROM EMPLOYEES WHERE IS_ACTIVE = FALSE;

-- 5.
SELECT * FROM EMPLOYEES;