CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10),
AGE INT,
CITY VARCHAR(10),
COURSE VARCHAR(10),
CGPA DECIMAL(10, 2)
);

DROP TABLE STUDENTS;

INSERT INTO STUDENTS 
(NAME, AGE, CITY, COURSE, CGPA) VALUES
('NIKHIL', 21, 'KADI', 'BCA', 9.50),
('RAHUL', 22, 'AHMEDABAD', 'BCA', 7.80),
('PRIYA', 20, 'SURAT', 'C.COM', 9.10),
('AMIT', 23, 'KADI', 'BCA', 8.90),
('NEHA', 21, 'RAJKOT', 'B.SC', 7.50),
('KARAN', 24, 'AHMEDABAD', 'BCA', 6.90),
('RIYA', 22, 'SURAT', 'B.SC', 8.70),
('VISHAL', 20, 'KADI', 'B.COM', 7.20),
('POOJA', 23, 'RAJKOT', 'BCA', 9.40),
('ARJUN', 21, 'AHMEDABAD', 'B.SC', 8.10);

SELECT * FROM STUDENTS;

-- 1.
SELECT * FROM STUDENTS ORDER BY NAME ASC;

-- 2.
SELECT * FROM STUDENTS ORDER BY AGE ASC;

-- 3.
SELECT * FROM STUDENTS WHERE COURSE = 'BCA' ORDER BY CGPA DESC;

-- 4. 
SELECT * FROM STUDENTS ORDER BY AGE DESC, COURSE ASC;

-- 5.
SELECT * FROM STUDENTS ORDER BY CITY ASC, NAME ASC;