CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10),
AGE INT,
CITY VARCHAR(10),
COURSE VARCHAR(10),
CGPA DECIMAL(10, 2)
);

DROP TABLE STUDENTS;

INSERT INTO STUDENTS 
(NAME, AGE, CITY, COURSE, CGPA) VALUES
('NIKHIL', 21, 'KADI', 'BCA', 9.50),
('RAHUL', 22, 'AHMEDABAD', 'BCA', 7.80),
('PRIYA', 20, 'SURAT', 'C.COM', 9.10),
('AMIT', 23, 'KADI', 'BCA', 8.90),
('NEHA', 21, 'RAJKOT', 'B.SC', 7.50),
('KARAN', 24, 'AHMEDABAD', 'BCA', 6.90),
('RIYA', 22, 'SURAT', 'B.SC', 8.70),
('VISHAL', 20, 'KADI', 'B.COM', 7.20),
('POOJA', 23, 'RAJKOT', 'BCA', 9.40),
('ARJUN', 21, 'AHMEDABAD', 'B.SC', 8.10);

SELECT * FROM STUDENTS;

-- 1.
SELECT MAX(CGPA) FROM STUDENTS;

-- 2.
SELECT MIN(AGE) FROM STUDENTS;

-- 3.
SELECT MIN(AGE), MAX(AGE) FROM STUDENTS;

-- 4.
SELECT MIN(CGPA), MAX(CGPA), AVG(CGPA) FROM STUDENTS ORDER BY COURSE;

-- 5. 
SELECT NAME, CGPA FROM STUDENTS ORDER BY CGPA DESC LIMIT 1;