CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENTS(
  id INT PRIMARY KEY ,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(20) UNIQUE NOT NULL,
  age INT CHECK (age >= 1),
  city VARCHAR(10) DEFAULT 'KADI',
  course VARCHAR(10) NOT NULL,
  cgpa DECIMAL(10, 2)
);

DESCRIBE STUDENTS;