CREATE DATABASE SCHOOL;

USE SCHOOL;


-- 1 STUDENTS TABLE 
CREATE TABLE STUDENTS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
GENDER ENUM('M', 'F') NOT NULL,
DOB DATE NOT NULL
);


-- 2  TEACHERS TABLE
CREATE TABLE TEACHERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
GENDER ENUM('M', 'F') NOT NULL,
SUBJECT VARCHAR(15),
SALARY DECIMAL(10, 2) NOT NULL,
DATE_JOINED TIMESTAMP DEFAULT NOW()
);

-- 3 COURSES TABLE
CREATE TABLE COURSES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(15) NOT NULL,
SUBJECTS INT NOT NULL,
FEES FLOAT NOT NULL,
IN_TAKE INT DEFAULT 120
);