CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE STUDENT (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(10)
);

INSERT INTO STUDENT VALUES
(1, 'TUSHAR', 19, 'MODASHA');

INSERT INTO STUDENT 
(NAME, AGE, CITY) VALUES
('VANSH', 19, 'KADI'),
('NIKHIL', 17, 'KADI'),
('ZEESHAN', 20, 'SAUDI'),
('PREM', 18, 'KADI');

INSERT INTO STUDENT (NAME, AGE) VALUES
('NIRMESH', 50);

SELECT * FROM STUDENT;

