CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE STUDENT (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(10)
);

INSERT INTO STUDENT 
(NAME, AGE, CITY) VALUES
('VANSH', 19, 'KADI'),
('NIKHIL', 17, 'KADI'),
('ZEESHAN', 20, 'SAUDI'),
('PREM', 18, 'KADI'),
('NIRMESH', 50, 'AHMEDABAD'),
('TUSHAR', 19, 'MODASHA');

SELECT NAME, CITY FROM STUDENT;

SELECT DISTINCT CITY FROM STUDENT;

SELECT * FROM STUDENT LIMIT 3;

SELECT NAME AS "Student Name", CITY AS "Home City" FROM STUDENT;

SELECT * FROM STUDENT LIMIT 2 OFFSET 3;