CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE STUDENT2 (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(10) NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(10)
);


INSERT INTO STUDENT 
(NAME, AGE, CITY) VALUES
('VANSH', 19, 'KADI'),
('NIKHIL', 17, 'KADI'),
('ZEESHAN', 20, 'SAUDI'),
('PREM', 18, 'KADI'),
('NIRMESH', 50, 'AHMEDABAD'),
('TUSHAR', 19, 'MODASHA');

SELECT * FROM STUDENT WHERE CITY = 'KADI';

SELECT * FROM STUDENT WHERE AGE > 20;

SELECT * FROM STUDENT WHERE CITY = 'KADI' AND AGE > 18;

SELECT * FROM STUDENT WHERE CITY = 'SAUDI' OR CITY = 'AHMEDABAD';

SELECT * FROM STUDENT WHERE NOT CITY = 'KADI';

SELECT * FROM STUDENT WHERE AGE BETWEEN 19 AND 23;

SELECT * FROM STUDENT WHERE CITY IN('KADI', 'SURAT', 'AHMEDABAD');

SELECT * FROM STUDENT WHERE NAME LIKE "N%";

SELECT * FROM STUDENT WHERE NAME LIKE "%IL";

SELECT * FROM STUDENT WHERE CITY IS NULL;

SELECT * FROM STUDENT WHERE CITY IS NOT NULL;